eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/
      
okta:
  oauth2:
    issuer: https://dev-15585796.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411
    
